#ifndef TRACKITEM_H
#define TRACKITEM_H

#include <QWidget>
#include <QMouseEvent>

#include "playlistmanager.h"
#include "roundedpixmap.h"

namespace Ui {
class trackItem;
}

class TrackItem : public QWidget
{
    Q_OBJECT

public:
    PlaylistManager::Track track;

    explicit TrackItem(QWidget *parent = nullptr);

    /*!
     * \brief setAttributes
     * \param index Autogenerated index of track.
     * \param title Title of track.
     * \param artist Artist of track.
     * \param fileLocation File location of track.
     */
    void setAttributes(int index, std::string title, std::string artist, std::string fileLocation);

    /*!
     * \brief setAttributes
     * \param index Autogenerated index of playlist.
     * \param title Title of playlist.
     */
    void setAttributes(int index, const char* title);
    ~TrackItem();

    /*!
     * \brief getTrack
     * \return Track object.
     */
    PlaylistManager::Track getTrack();

signals:
    /*!
     * \brief clicked
     */
    void clicked(TrackItem*);

protected:
    /*!
     * \brief mousePressEvent
     * \param event
     */
    void mousePressEvent(QMouseEvent *event){
        emit clicked(this);
        QWidget::mousePressEvent(event);
    }

private:
    Ui::trackItem *ui;
};

#endif // TRACKITEM_H
